# Generated by Django 4.1.4 on 2023-01-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_endgame_endgame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightModel',
            new_name='InFlight',
        ),
    ]
