# Generated by Django 4.1.4 on 2023-01-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_flightmodel_inflight'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflight',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.startgame'),
        ),
    ]
