# Generated by Django 4.1.4 on 2023-01-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_bounce_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounce',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
