# Generated by Django 4.1.4 on 2023-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_bounce_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounce',
            name='game',
        ),
        migrations.RemoveField(
            model_name='inflight',
            name='game',
        ),
        migrations.AlterField(
            model_name='gamefinish',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
